// Code generated by MockGen. DO NOT EDIT.
// Source: core/routing.go

// Package mock is a generated GoMock package.
package mock

import (
	entity "github.com/codefluence-x/altair/entity"
	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRouteCompiler is a mock of RouteCompiler interface
type MockRouteCompiler struct {
	ctrl     *gomock.Controller
	recorder *MockRouteCompilerMockRecorder
}

// MockRouteCompilerMockRecorder is the mock recorder for MockRouteCompiler
type MockRouteCompilerMockRecorder struct {
	mock *MockRouteCompiler
}

// NewMockRouteCompiler creates a new mock instance
func NewMockRouteCompiler(ctrl *gomock.Controller) *MockRouteCompiler {
	mock := &MockRouteCompiler{ctrl: ctrl}
	mock.recorder = &MockRouteCompilerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouteCompiler) EXPECT() *MockRouteCompilerMockRecorder {
	return m.recorder
}

// Compile mocks base method
func (m *MockRouteCompiler) Compile(path string) []entity.RouteObject {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compile", path)
	ret0, _ := ret[0].([]entity.RouteObject)
	return ret0
}

// Compile indicates an expected call of Compile
func (mr *MockRouteCompilerMockRecorder) Compile(path interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compile", reflect.TypeOf((*MockRouteCompiler)(nil).Compile), path)
}

// MockRouteGenerator is a mock of RouteGenerator interface
type MockRouteGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockRouteGeneratorMockRecorder
}

// MockRouteGeneratorMockRecorder is the mock recorder for MockRouteGenerator
type MockRouteGeneratorMockRecorder struct {
	mock *MockRouteGenerator
}

// NewMockRouteGenerator creates a new mock instance
func NewMockRouteGenerator(ctrl *gomock.Controller) *MockRouteGenerator {
	mock := &MockRouteGenerator{ctrl: ctrl}
	mock.recorder = &MockRouteGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRouteGenerator) EXPECT() *MockRouteGeneratorMockRecorder {
	return m.recorder
}

// Generate mocks base method
func (m *MockRouteGenerator) Generate(c *gin.Engine, routeObjects []entity.RouteObject) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Generate", c, routeObjects)
}

// Generate indicates an expected call of Generate
func (mr *MockRouteGeneratorMockRecorder) Generate(c, routeObjects interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockRouteGenerator)(nil).Generate), c, routeObjects)
}
