// Code generated by MockGen. DO NOT EDIT.
// Source: core/validator.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	entity "github.com/codefluence-x/altair/entity"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockOauthApplicationValidator is a mock of OauthApplicationValidator interface
type MockOauthApplicationValidator struct {
	ctrl     *gomock.Controller
	recorder *MockOauthApplicationValidatorMockRecorder
}

// MockOauthApplicationValidatorMockRecorder is the mock recorder for MockOauthApplicationValidator
type MockOauthApplicationValidatorMockRecorder struct {
	mock *MockOauthApplicationValidator
}

// NewMockOauthApplicationValidator creates a new mock instance
func NewMockOauthApplicationValidator(ctrl *gomock.Controller) *MockOauthApplicationValidator {
	mock := &MockOauthApplicationValidator{ctrl: ctrl}
	mock.recorder = &MockOauthApplicationValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOauthApplicationValidator) EXPECT() *MockOauthApplicationValidatorMockRecorder {
	return m.recorder
}

// ValidateCreate mocks base method
func (m *MockOauthApplicationValidator) ValidateCreate(ctx context.Context, data entity.OauthApplicationJSON) *entity.Error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCreate", ctx, data)
	ret0, _ := ret[0].(*entity.Error)
	return ret0
}

// ValidateCreate indicates an expected call of ValidateCreate
func (mr *MockOauthApplicationValidatorMockRecorder) ValidateCreate(ctx, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCreate", reflect.TypeOf((*MockOauthApplicationValidator)(nil).ValidateCreate), ctx, data)
}
