// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mock is a generated GoMock package.
package mock

import (
	http "net/http"
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "github.com/golang/mock/gomock"
	module "github.com/kodefluence/altair/module"
	jsonapi "github.com/kodefluence/monorepo/jsonapi"
	kontext "github.com/kodefluence/monorepo/kontext"
	cobra "github.com/spf13/cobra"
	pflag "github.com/spf13/pflag"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// Controller mocks base method.
func (m *MockApp) Controller() module.Controller {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Controller")
	ret0, _ := ret[0].(module.Controller)
	return ret0
}

// Controller indicates an expected call of Controller.
func (mr *MockAppMockRecorder) Controller() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Controller", reflect.TypeOf((*MockApp)(nil).Controller))
}

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// InjectCommand mocks base method.
func (m *MockController) InjectCommand(command ...module.CommandController) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range command {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InjectCommand", varargs...)
}

// InjectCommand indicates an expected call of InjectCommand.
func (mr *MockControllerMockRecorder) InjectCommand(command ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectCommand", reflect.TypeOf((*MockController)(nil).InjectCommand), command...)
}

// InjectDownstream mocks base method.
func (m *MockController) InjectDownstream(downstream ...module.DownstreamController) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range downstream {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InjectDownstream", varargs...)
}

// InjectDownstream indicates an expected call of InjectDownstream.
func (mr *MockControllerMockRecorder) InjectDownstream(downstream ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectDownstream", reflect.TypeOf((*MockController)(nil).InjectDownstream), downstream...)
}

// InjectHTTP mocks base method.
func (m *MockController) InjectHTTP(http ...module.HttpController) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range http {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InjectHTTP", varargs...)
}

// InjectHTTP indicates an expected call of InjectHTTP.
func (mr *MockControllerMockRecorder) InjectHTTP(http ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectHTTP", reflect.TypeOf((*MockController)(nil).InjectHTTP), http...)
}

// InjectMetric mocks base method.
func (m *MockController) InjectMetric(http ...module.MetricController) {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range http {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InjectMetric", varargs...)
}

// InjectMetric indicates an expected call of InjectMetric.
func (mr *MockControllerMockRecorder) InjectMetric(http ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectMetric", reflect.TypeOf((*MockController)(nil).InjectMetric), http...)
}

// ListDownstream mocks base method.
func (m *MockController) ListDownstream() []module.DownstreamController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDownstream")
	ret0, _ := ret[0].([]module.DownstreamController)
	return ret0
}

// ListDownstream indicates an expected call of ListDownstream.
func (mr *MockControllerMockRecorder) ListDownstream() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDownstream", reflect.TypeOf((*MockController)(nil).ListDownstream))
}

// ListMetric mocks base method.
func (m *MockController) ListMetric() []module.MetricController {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListMetric")
	ret0, _ := ret[0].([]module.MetricController)
	return ret0
}

// ListMetric indicates an expected call of ListMetric.
func (mr *MockControllerMockRecorder) ListMetric() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListMetric", reflect.TypeOf((*MockController)(nil).ListMetric))
}

// MockMetricController is a mock of MetricController interface.
type MockMetricController struct {
	ctrl     *gomock.Controller
	recorder *MockMetricControllerMockRecorder
}

// MockMetricControllerMockRecorder is the mock recorder for MockMetricController.
type MockMetricControllerMockRecorder struct {
	mock *MockMetricController
}

// NewMockMetricController creates a new mock instance.
func NewMockMetricController(ctrl *gomock.Controller) *MockMetricController {
	mock := &MockMetricController{ctrl: ctrl}
	mock.recorder = &MockMetricControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetricController) EXPECT() *MockMetricControllerMockRecorder {
	return m.recorder
}

// Inc mocks base method.
func (m *MockMetricController) Inc(metricName string, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Inc", metricName, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// Inc indicates an expected call of Inc.
func (mr *MockMetricControllerMockRecorder) Inc(metricName, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Inc", reflect.TypeOf((*MockMetricController)(nil).Inc), metricName, labels)
}

// InjectCounter mocks base method.
func (m *MockMetricController) InjectCounter(metricName string, labels ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{metricName}
	for _, a := range labels {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InjectCounter", varargs...)
}

// InjectCounter indicates an expected call of InjectCounter.
func (mr *MockMetricControllerMockRecorder) InjectCounter(metricName interface{}, labels ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metricName}, labels...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectCounter", reflect.TypeOf((*MockMetricController)(nil).InjectCounter), varargs...)
}

// InjectHistogram mocks base method.
func (m *MockMetricController) InjectHistogram(metricName string, labels ...string) {
	m.ctrl.T.Helper()
	varargs := []interface{}{metricName}
	for _, a := range labels {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "InjectHistogram", varargs...)
}

// InjectHistogram indicates an expected call of InjectHistogram.
func (mr *MockMetricControllerMockRecorder) InjectHistogram(metricName interface{}, labels ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{metricName}, labels...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InjectHistogram", reflect.TypeOf((*MockMetricController)(nil).InjectHistogram), varargs...)
}

// Observe mocks base method.
func (m *MockMetricController) Observe(metricName string, value float64, labels map[string]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Observe", metricName, value, labels)
	ret0, _ := ret[0].(error)
	return ret0
}

// Observe indicates an expected call of Observe.
func (mr *MockMetricControllerMockRecorder) Observe(metricName, value, labels interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Observe", reflect.TypeOf((*MockMetricController)(nil).Observe), metricName, value, labels)
}

// MockHttpController is a mock of HttpController interface.
type MockHttpController struct {
	ctrl     *gomock.Controller
	recorder *MockHttpControllerMockRecorder
}

// MockHttpControllerMockRecorder is the mock recorder for MockHttpController.
type MockHttpControllerMockRecorder struct {
	mock *MockHttpController
}

// NewMockHttpController creates a new mock instance.
func NewMockHttpController(ctrl *gomock.Controller) *MockHttpController {
	mock := &MockHttpController{ctrl: ctrl}
	mock.recorder = &MockHttpControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpController) EXPECT() *MockHttpControllerMockRecorder {
	return m.recorder
}

// Control mocks base method.
func (m *MockHttpController) Control(ktx kontext.Context, c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Control", ktx, c)
}

// Control indicates an expected call of Control.
func (mr *MockHttpControllerMockRecorder) Control(ktx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Control", reflect.TypeOf((*MockHttpController)(nil).Control), ktx, c)
}

// Method mocks base method.
func (m *MockHttpController) Method() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Method")
	ret0, _ := ret[0].(string)
	return ret0
}

// Method indicates an expected call of Method.
func (mr *MockHttpControllerMockRecorder) Method() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Method", reflect.TypeOf((*MockHttpController)(nil).Method))
}

// Path mocks base method.
func (m *MockHttpController) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockHttpControllerMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockHttpController)(nil).Path))
}

// MockCommandController is a mock of CommandController interface.
type MockCommandController struct {
	ctrl     *gomock.Controller
	recorder *MockCommandControllerMockRecorder
}

// MockCommandControllerMockRecorder is the mock recorder for MockCommandController.
type MockCommandControllerMockRecorder struct {
	mock *MockCommandController
}

// NewMockCommandController creates a new mock instance.
func NewMockCommandController(ctrl *gomock.Controller) *MockCommandController {
	mock := &MockCommandController{ctrl: ctrl}
	mock.recorder = &MockCommandControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommandController) EXPECT() *MockCommandControllerMockRecorder {
	return m.recorder
}

// Example mocks base method.
func (m *MockCommandController) Example() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Example")
	ret0, _ := ret[0].(string)
	return ret0
}

// Example indicates an expected call of Example.
func (mr *MockCommandControllerMockRecorder) Example() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Example", reflect.TypeOf((*MockCommandController)(nil).Example))
}

// ModifyFlags mocks base method.
func (m *MockCommandController) ModifyFlags(flags *pflag.FlagSet) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ModifyFlags", flags)
}

// ModifyFlags indicates an expected call of ModifyFlags.
func (mr *MockCommandControllerMockRecorder) ModifyFlags(flags interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ModifyFlags", reflect.TypeOf((*MockCommandController)(nil).ModifyFlags), flags)
}

// Run mocks base method.
func (m *MockCommandController) Run(cmd *cobra.Command, args []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", cmd, args)
}

// Run indicates an expected call of Run.
func (mr *MockCommandControllerMockRecorder) Run(cmd, args interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCommandController)(nil).Run), cmd, args)
}

// Short mocks base method.
func (m *MockCommandController) Short() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Short")
	ret0, _ := ret[0].(string)
	return ret0
}

// Short indicates an expected call of Short.
func (mr *MockCommandControllerMockRecorder) Short() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Short", reflect.TypeOf((*MockCommandController)(nil).Short))
}

// Use mocks base method.
func (m *MockCommandController) Use() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Use")
	ret0, _ := ret[0].(string)
	return ret0
}

// Use indicates an expected call of Use.
func (mr *MockCommandControllerMockRecorder) Use() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Use", reflect.TypeOf((*MockCommandController)(nil).Use))
}

// MockDownstreamController is a mock of DownstreamController interface.
type MockDownstreamController struct {
	ctrl     *gomock.Controller
	recorder *MockDownstreamControllerMockRecorder
}

// MockDownstreamControllerMockRecorder is the mock recorder for MockDownstreamController.
type MockDownstreamControllerMockRecorder struct {
	mock *MockDownstreamController
}

// NewMockDownstreamController creates a new mock instance.
func NewMockDownstreamController(ctrl *gomock.Controller) *MockDownstreamController {
	mock := &MockDownstreamController{ctrl: ctrl}
	mock.recorder = &MockDownstreamControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDownstreamController) EXPECT() *MockDownstreamControllerMockRecorder {
	return m.recorder
}

// Intervene mocks base method.
func (m *MockDownstreamController) Intervene(c *gin.Context, proxyReq *http.Request, r module.RouterPath) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Intervene", c, proxyReq, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Intervene indicates an expected call of Intervene.
func (mr *MockDownstreamControllerMockRecorder) Intervene(c, proxyReq, r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Intervene", reflect.TypeOf((*MockDownstreamController)(nil).Intervene), c, proxyReq, r)
}

// Name mocks base method.
func (m *MockDownstreamController) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockDownstreamControllerMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockDownstreamController)(nil).Name))
}

// MockApiError is a mock of ApiError interface.
type MockApiError struct {
	ctrl     *gomock.Controller
	recorder *MockApiErrorMockRecorder
}

// MockApiErrorMockRecorder is the mock recorder for MockApiError.
type MockApiErrorMockRecorder struct {
	mock *MockApiError
}

// NewMockApiError creates a new mock instance.
func NewMockApiError(ctrl *gomock.Controller) *MockApiError {
	mock := &MockApiError{ctrl: ctrl}
	mock.recorder = &MockApiErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiError) EXPECT() *MockApiErrorMockRecorder {
	return m.recorder
}

// BadRequestError mocks base method.
func (m *MockApiError) BadRequestError(in string) jsonapi.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BadRequestError", in)
	ret0, _ := ret[0].(jsonapi.Option)
	return ret0
}

// BadRequestError indicates an expected call of BadRequestError.
func (mr *MockApiErrorMockRecorder) BadRequestError(in interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BadRequestError", reflect.TypeOf((*MockApiError)(nil).BadRequestError), in)
}

// ForbiddenError mocks base method.
func (m *MockApiError) ForbiddenError(ktx kontext.Context, entityType, reason string) jsonapi.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ForbiddenError", ktx, entityType, reason)
	ret0, _ := ret[0].(jsonapi.Option)
	return ret0
}

// ForbiddenError indicates an expected call of ForbiddenError.
func (mr *MockApiErrorMockRecorder) ForbiddenError(ktx, entityType, reason interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ForbiddenError", reflect.TypeOf((*MockApiError)(nil).ForbiddenError), ktx, entityType, reason)
}

// InternalServerError mocks base method.
func (m *MockApiError) InternalServerError(ktx kontext.Context) jsonapi.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InternalServerError", ktx)
	ret0, _ := ret[0].(jsonapi.Option)
	return ret0
}

// InternalServerError indicates an expected call of InternalServerError.
func (mr *MockApiErrorMockRecorder) InternalServerError(ktx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalServerError", reflect.TypeOf((*MockApiError)(nil).InternalServerError), ktx)
}

// NotFoundError mocks base method.
func (m *MockApiError) NotFoundError(ktx kontext.Context, entityType string) jsonapi.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotFoundError", ktx, entityType)
	ret0, _ := ret[0].(jsonapi.Option)
	return ret0
}

// NotFoundError indicates an expected call of NotFoundError.
func (mr *MockApiErrorMockRecorder) NotFoundError(ktx, entityType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFoundError", reflect.TypeOf((*MockApiError)(nil).NotFoundError), ktx, entityType)
}

// UnauthorizedError mocks base method.
func (m *MockApiError) UnauthorizedError() jsonapi.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnauthorizedError")
	ret0, _ := ret[0].(jsonapi.Option)
	return ret0
}

// UnauthorizedError indicates an expected call of UnauthorizedError.
func (mr *MockApiErrorMockRecorder) UnauthorizedError() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnauthorizedError", reflect.TypeOf((*MockApiError)(nil).UnauthorizedError))
}

// ValidationError mocks base method.
func (m *MockApiError) ValidationError(msg string) jsonapi.Option {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidationError", msg)
	ret0, _ := ret[0].(jsonapi.Option)
	return ret0
}

// ValidationError indicates an expected call of ValidationError.
func (mr *MockApiErrorMockRecorder) ValidationError(msg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidationError", reflect.TypeOf((*MockApiError)(nil).ValidationError), msg)
}

// MockRouterPath is a mock of RouterPath interface.
type MockRouterPath struct {
	ctrl     *gomock.Controller
	recorder *MockRouterPathMockRecorder
}

// MockRouterPathMockRecorder is the mock recorder for MockRouterPath.
type MockRouterPathMockRecorder struct {
	mock *MockRouterPath
}

// NewMockRouterPath creates a new mock instance.
func NewMockRouterPath(ctrl *gomock.Controller) *MockRouterPath {
	mock := &MockRouterPath{ctrl: ctrl}
	mock.recorder = &MockRouterPathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouterPath) EXPECT() *MockRouterPathMockRecorder {
	return m.recorder
}

// GetAuth mocks base method.
func (m *MockRouterPath) GetAuth() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuth")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuth indicates an expected call of GetAuth.
func (mr *MockRouterPathMockRecorder) GetAuth() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuth", reflect.TypeOf((*MockRouterPath)(nil).GetAuth))
}

// GetScope mocks base method.
func (m *MockRouterPath) GetScope() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetScope")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetScope indicates an expected call of GetScope.
func (mr *MockRouterPathMockRecorder) GetScope() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetScope", reflect.TypeOf((*MockRouterPath)(nil).GetScope))
}
